FROM node:20-alpine

WORKDIR /app

RUN npm install -g vite typescript

COPY package*.json ./

RUN npm install

COPY . .

ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true
ENV VITE_API_URL=http://gateway:3000/api

EXPOSE 3000

CMD ["vite"]
